# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOSProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IOSProject

pod 'AFNetworking', '~> 3.1'

pod 'SDWebImage', '~> 3.8'

pod 'FBSDKCoreKit', '~> 4.17'
pod 'FBSDKLoginKit', '~> 4.17'
pod 'FBSDKShareKit', '~> 4.17'
end
